In [2]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.insert(0, "../src/")
sys.path.insert(0, "../projects/skimpy_bench/src/")
sys.path.insert(0, "../projects/skimpy_blox/")

import math
import functools
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path

import skimpy
import _skimpy_cpp_ext
import _skimpy_bench_cpp_ext
from skimpy import config as skimpy_config
from skimpy_bench import benchmarks
from skimpy_blox.minecraft import SkimpyMinecraftLevel

sns.set()


In [6]:
with pyskip_config.lazy_evaluation_scope():
    x = pyskip.Tensor((3, 3), val=3)
    y = pyskip.Tensor((3, 3), val=4)
    z = pyskip.Tensor((3, 3), val=5)
    
    middle = x + y
    out = middle + z

print(out)

[[12 12 12]
 [12 12 12]
 [12 12 12]]


In [2]:
b = benchmarks.RunLengthArrayBenchmark(
    num_non_zero=10_000_000,
    array_length=512 * 1024 * 1024,
    num_inputs=32,
    align_inputs=False,
    deterministic_run_length=True,
    run_length=100,
)

In [14]:
inputs = [_skimpy_cpp_ext.from_numpy(t) for t in b._numpy_inputs()]

In [15]:
for i in range(1000):
    b.run_skimpy(num_threads=32, inputs=inputs)

KeyboardInterrupt: 

In [10]:
a = skimpy.Tensor((2, 2), val=0)
b = skimpy.Tensor((2, 2), val=0)
c = skimpy.Tensor((2, 2), val=0)

a[1,0] = 10
b[1,0] = 10
c[1,0] = 10

In [14]:
(a + b + c).eval()

Tensor(shape=(2, 2), dtype=int):
    [[ 0, 30],
     [ 0,  0]]