In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.insert(0, "../src/")
sys.path.insert(0, "../projects/pyskip_bench/src/")
sys.path.insert(0, "../projects/pyskip_blox/")

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pyskip
import pyskip.config as pyskip_config

In [7]:
with pyskip_config.config_scope(custom_eval_kernel="add_int32"):
    print(pyskip_config.get_all_values())
    a = pyskip.Tensor(shape=(3,3), val=2)
    b = pyskip.Tensor(shape=(3,3), val=1)
    
    print(a + b + b)

{'custom_eval_kernel': 'add_int32'}
[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [3]:
a = pyskip.Tensor(shape=(3,3), val=2)
b = pyskip.Tensor(shape=(3,3), val=1)
    
a + b

Tensor(shape=(3, 3), dtype=int):
    [[3, 3, 3],
     [3, 3, 3],
     [3, 3, 3]]

In [1]:
for i in range(65, 257):
    print(f"""case {i}: return execute_plan_fixed<Val, {i}>(std::move(plan));""")

case 65: return execute_plan_fixed<Val, 65>(std::move(plan));
case 66: return execute_plan_fixed<Val, 66>(std::move(plan));
case 67: return execute_plan_fixed<Val, 67>(std::move(plan));
case 68: return execute_plan_fixed<Val, 68>(std::move(plan));
case 69: return execute_plan_fixed<Val, 69>(std::move(plan));
case 70: return execute_plan_fixed<Val, 70>(std::move(plan));
case 71: return execute_plan_fixed<Val, 71>(std::move(plan));
case 72: return execute_plan_fixed<Val, 72>(std::move(plan));
case 73: return execute_plan_fixed<Val, 73>(std::move(plan));
case 74: return execute_plan_fixed<Val, 74>(std::move(plan));
case 75: return execute_plan_fixed<Val, 75>(std::move(plan));
case 76: return execute_plan_fixed<Val, 76>(std::move(plan));
case 77: return execute_plan_fixed<Val, 77>(std::move(plan));
case 78: return execute_plan_fixed<Val, 78>(std::move(plan));
case 79: return execute_plan_fixed<Val, 79>(std::move(plan));
case 80: return execute_plan_fixed<Val, 80>(std::move(plan));
case 81: